# Generated by Django 5.2.7 on 2025-11-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_name', models.CharField(max_length=100)),
                ('element_formula', models.CharField(max_length=1000)),
                ('element_description', models.TextField()),
            ],
        ),
    ]
