# Generated by Django 5.2.7 on 2025-11-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=1000)),
                ('school_branch', models.CharField(max_length=1200)),
                ('school_detail', models.TextField()),
            ],
        ),
    ]
