# Generated by Django 5.2.7 on 2025-11-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_name', models.CharField(max_length=150)),
                ('fruit_name', models.CharField(max_length=100)),
                ('height', models.IntegerField()),
            ],
        ),
    ]
