# Generated by Django 5.2.7 on 2025-11-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_tree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='age',
            field=models.IntegerField(),
        ),
    ]
